$ErrorActionPreference = 'Continue'
$secure = Read-Host -AsSecureString
$ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
try { $key = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr) }
$dir = 'F:\英语网页重构\docs\design\ui-variants-20260926'
$cli = 'F:\CodexHome\skills\autoGenImageSkill\scripts\gpt_image_cli.js'
$jobs = @(
  @{ n='eastudy-ui-v02-rose-cream.png'; p='High-fidelity product UI design board, not a photo. Eastudy English-learning mobile app for mostly female users. Based on the supplied reference images, show two coordinated 390x844 screens: mobile video player detail and vocabulary card. Preserve the exact proven button positions and information hierarchy: top title bar, edge-to-edge video, compact mode row, subtitle stream with speaker and star, fixed bottom bar with speed, blind listening, previous, centered play, next, more, and bottom stats. Vocabulary card has play it by ear, IPA, 习语, 核心释义, 语境理解, contextual example, 播放原句, 复制, 加入生词本. Variant 02 color system: mature rose cream, porcelain white, dusty rose primary #B65F83, pale pink #FCEAF1, warm amber underlines #B06B14, dark mauve text. Elegant feminine but not childish, crisp Chinese typography, English serif. No desktop layout, no extra controls, no gradients, no purple, no 3D, no watermark, no random text.' },
  @{ n='eastudy-ui-v03-sage-ivory.png'; p='High-fidelity product UI design board, not a photo. Eastudy English-learning mobile app for mostly female users. Based on the supplied reference images, show two coordinated 390x844 screens: mobile video player detail and vocabulary card. Preserve exact mature layout and button positions: top bar, full-width video, mode pills, subtitle list, fixed compact controls, stats row, vocabulary card structure. Variant 03 color system: calm sage green and ivory, primary #568A78, pale sage #E8F3EC, warm amber advanced-word underline #A36D18, deep forest text. Sophisticated natural feminine editorial aesthetic, no childish decoration. Crisp Chinese UI, readable English serif. No desktop layout, no extra controls, no gradients, no purple, no 3D, no watermark, no random text.' },
  @{ n='eastudy-ui-v04-lavender-gray.png'; p='High-fidelity product UI design board, not a photo. Eastudy English-learning mobile app for mostly female users. Based on the supplied reference images, show two coordinated 390x844 screens: mobile video player detail and vocabulary card. Preserve exact mature layout and button positions: title bar, edge-to-edge video, mode row, subtitle stream, fixed bottom player controls, bottom stats, card with play it by ear and three actions. Variant 04 color system: restrained lavender gray and white, primary #7564AE, soft lavender #EFECFA, amber expression underlines #A36C16, deep charcoal-plum text. Premium calm feminine app aesthetic, not sweet or childish. Crisp Chinese labels and readable English serif. No desktop layout, no extra controls, no gradients, no purple bias, no 3D, no watermark, no random text.' },
  @{ n='eastudy-ui-v05-coral-sand.png'; p='High-fidelity product UI design board, not a photo. Eastudy English-learning mobile app for mostly female users. Based on the supplied reference images, show two coordinated 390x844 screens: mobile video player detail and vocabulary card. Preserve exact mature layout and button positions: top bar, full-width video, compact mode pills, subtitle stream with speaker/star, fixed bottom controls, stats row, card with play it by ear, IPA, meaning, context and actions. Variant 05 color system: soft coral and almond sand, primary #D3735B, pale coral #FDEBE3, warm amber #A76515 for advanced phrases, cocoa text. Warm polished feminine editorial UI, restrained and comfortable for long study sessions. No desktop layout, no extra controls, no gradients, no purple, no 3D, no watermark, no random text.' },
  @{ n='eastudy-ui-v06-midnight-blue.png'; p='High-fidelity product UI design board, not a photo. Eastudy English-learning mobile app for mostly female users. Based on the supplied reference images, show two coordinated 390x844 screens: dark mobile video player detail and dark vocabulary card. Preserve exact mature layout and button positions: top title bar, edge-to-edge video, mode pills, subtitle stream with amber highlighted phrases, fixed bottom controls, bottom stats, vocabulary card with play it by ear, IPA, 习语, 核心释义, 语境理解, example and three actions. Variant 06 color system: deep midnight navy #102239 and #182E49, luminous sky blue #61B1EE, warm gold #F0BB58, soft blue-gray text. Premium quiet night-study aesthetic, readable and not neon. No desktop layout, no extra controls, no gradients, no purple, no 3D, no watermark, no random text.' }
)
foreach ($job in $jobs) {
  Write-Output "GENERATING $($job.n)"
  node $cli generate --mode proxy --base-url 'https://coldcoffeeai.com/v1' --api-key $key --endpoint-mode images --image-model gpt-image-2 --size 1024x1536 --quality high --retries 1 --prompt $job.p --output (Join-Path $dir $job.n)
}
$key = $null
